_security_login:
    pattern:  /login
    defaults: { _controller: AppBundle:Security:login }

_security_check:
    pattern:  /login_check

_security_logout:
    pattern:  /logout

admin_home:
    pattern:  /play/*
    defaults: { _controller: AppBundle:Default:index }

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /play
        permanent: true
